## Pandas Tutorial

In [ ]:
# pandas package-ni install edirik
# !pip install pandas

In [1]:
import pandas as pd
import numpy as np

In [3]:
# csv fayl əsasında dataframe obyektini yaradırıq
df = pd.read_csv('tutorial9.csv')
df1 = df.copy()

In [4]:
# dataframe-in ilk n (default=5) sətirinı baxırıq
df.head()

,number,pokemon_name,pic_url,main_type,secondary_type,region,category,height,weight,pokemon_family,...,resistance,weakness,wild_avail,egg_avail,raid_avail,research_avail,shiny,shadow,pkedex_desc,poss_attacks
0,1,Bulbasaur,https://static.wikia.nocookie.net/pokemongo/im...,Grass,Poison,Kanto,Seed,0.7 m,6.9 kg,Bulbasaur family,...,"{'62.5%': ['Electric', 'Fairy', 'Fighting', 'W...","{'160%': ['Fire', 'Flying', 'Ice', 'Psychic']}",Yes,No,Formerly (1st tier level),Yes,Yes,Yes,Bulbasaur can be seen napping in bright sunlig...,"['Tackle', 'Vine Whip', 'Power Whip', 'Seed Bo..."
1,2,Ivysaur,https://static.wikia.nocookie.net/pokemongo/im...,Grass,Poison,Kanto,Seed,1 m,13 kg,Bulbasaur family,...,"{'62.5%': ['Electric', 'Fairy', 'Fighting', 'W...","{'160%': ['Fire', 'Flying', 'Ice', 'Psychic']}",Yes,No,Formerly (1st tier level),No,Yes,Yes,There is a bud on this Pokémon's back. To supp...,"['Razor Leaf', 'Vine Whip', 'Power Whip', 'Slu..."
2,3,Venusaur,https://static.wikia.nocookie.net/pokemongo/im...,Grass,Poison,Kanto,Seed,2 m,100 kg,Bulbasaur family,...,"{'62.5%': ['Electric', 'Fairy', 'Fighting', 'W...","{'160%': ['Fire', 'Flying', 'Ice', 'Psychic']}",Yes,No,Formerly (3rd tier level),Formerly,Yes,Yes,Standard Pokédex description\nThere is a large...,"['Razor Leaf', 'Vine Whip', 'Petal Blizzard', ..."
3,4,Charmander,https://static.wikia.nocookie.net/pokemongo/im...,Fire,NaN,Kanto,Lizard,0.6 m,8.5 kg,Charmander family,...,"{'62.5%': ['Bug', 'Fairy', 'Fire', 'Grass', 'I...","{'160%': ['Ground', 'Rock', 'Water']}",Yes,No,Formerly (1st tier level),Yes,Yes,Yes,The flame that burns at the tip of its tail is...,"['Ember', 'Scratch', 'Flame Burst', 'Flame Cha..."
4,5,Charmeleon,https://static.wikia.nocookie.net/pokemongo/im...,Fire,NaN,Kanto,Flame,1.1 m,19 kg,Charmander family,...,"{'62.5%': ['Bug', 'Fairy', 'Fire', 'Grass', 'I...","{'160%': ['Ground', 'Rock', 'Water']}",Yes,No,Formerly (2nd tier level),Formerly,Yes,Yes,Charmeleon mercilessly destroys its foes using...,"['Ember', 'Fire Fang', 'Scratch', 'Fire Punch'..."

In [5]:
# dataframe-in son n (default=5) sətirinı baxırıq
df.tail()

,number,pokemon_name,pic_url,main_type,secondary_type,region,category,height,weight,pokemon_family,...,resistance,weakness,wild_avail,egg_avail,raid_avail,research_avail,shiny,shadow,pkedex_desc,poss_attacks
765,867,Runerigus,https://static.wikia.nocookie.net/pokemongo/im...,Ground,Ghost,Galar,Grudge,1.6 m,66.6 kg,Yamask family,...,"{'62.5%': ['Bug', 'Rock'], '39%': ['Electric',...","{'160%': ['Dark', 'Ghost', 'Grass', 'Ice', 'Wa...",No,No,No,No,No,No,A powerful curse was woven into an ancient pai...,"['Astonish', 'Rock Tomb', 'Sand Tomb', 'Shadow..."
766,870,Falinks,https://static.wikia.nocookie.net/pokemongo/im...,Fighting,NaN,Galar,Formation,3 m,62 kg,Falinks family,...,"{'62.5%': ['Bug', 'Dark', 'Rock']}","{'160%': ['Fairy', 'Flying', 'Psychic']}",Yes,No,No,Formerly,No,No,"Five of them are troopers, and one is the bras...","['Counter', 'Rock Smash', 'Brick Break', 'Mega..."
767,888,Zacian,"data:image/gif;base64,R0lGODlhAQABAIABAAAAAP//...",Fairy,NaN,Galar,Warrior,2.8 m,110 kg,Zacian family,...,"{'62.5%': ['Bug', 'Dark', 'Fighting'], '39%': ...","{'160%': ['Poison', 'Steel']}",No,No,Formerly (5th tier level),No,No,No,"Known as a legendary hero, this Pokémon absorb...","['Fire Fang', 'Metal Claw', 'Quick Attack', 'S..."
768,889,Zamazenta,"data:image/gif;base64,R0lGODlhAQABAIABAAAAAP//...",Fighting,NaN,Galar,Warrior,2.9 m,210 kg,Zamazenta family,...,"{'62.5%': ['Bug', 'Dark', 'Rock']}","{'160%': ['Fairy', 'Flying', 'Psychic']}",No,No,Formerly (5th tier level),No,No,No,"In times past, it worked together with a king ...","['Ice Fang', 'Metal Claw', 'Quick Attack', 'Sn..."
769,893,Zarude,"data:image/gif;base64,R0lGODlhAQABAIABAAAAAP//...",Dark,Grass,Galar,Rogue,1.8 m,70 kg,Zarude family,...,"{'62.5%': ['Dark', 'Electric', 'Ghost', 'Grass...","{'160%': ['Fairy', 'Fighting', 'Fire', 'Flying...",No,No,No,No,No,No,"Within dense forests, this Pokémon lives in a ...","['Bite', 'Vine Whip', 'Dark Pulse', 'Energy Ba..."

In [6]:
# cəmi 4 numeric sütunumuz var (həqiqətənmi?)
df.describe()

           number      attack     defense     stamina
count  770.000000  770.000000  770.000000  770.000000
mean   387.740260  161.861039  142.588312  169.062338
std    226.559919   55.817370   50.171027   44.214794
min      1.000000   17.000000   32.000000    1.000000
25%    193.250000  118.000000  102.250000  137.000000
50%    385.500000  161.000000  139.000000  163.000000
75%    577.750000  204.000000  176.000000  190.000000
max    893.000000  345.000000  396.000000  496.000000

In [7]:
# sütunların adlarına və data tiplərinə baxırıq
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 770 entries, 0 to 769
Data columns (total 29 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   number          770 non-null    int64
 1   pokemon_name    770 non-null    object
 2   pic_url         770 non-null    object
 3   main_type       770 non-null    object
 4   secondary_type  376 non-null    object
 5   region          770 non-null    object
 6   category        770 non-null    object
 7   height          770 non-null    object
 8   weight          770 non-null    object
 9   pokemon_family  770 non-null    object
 10  attack          770 non-null    int64
 11  defense         770 non-null    int64
 12  stamina         770 non-null    int64
 13  cp_range        770 non-null    object
 14  hp_range        770 non-null    object
 15  capture_rate    700 non-null    object
 16  flee_rate       700 non-null    object
 17  male_perc       611 non-null    object
 18  female_perc     611 non-null    object
 19  resistance      762 non-null    object
 20  weakness        762 non-null    object
 21  wild_avail      770 non-null    object
 22  egg_avail       770 non-null    object
 23  raid_avail      770 non-null    object
 24  research_avail  770 non-null    object
 25  shiny           770 non-null    object
 26  shadow          770 non-null    object
 27  pkedex_desc     770 non-null    object
 28  poss_attacks    770 non-null    object
dtypes: int64(4), object(25)
memory usage: 174.6+ KB

In [8]:
# NA qiymətləri yoxlayırıq.
df.isna().sum()

number              0
pokemon_name        0
pic_url             0
main_type           0
secondary_type    394
region              0
category            0
height              0
weight              0
pokemon_family      0
attack              0
defense             0
stamina             0
cp_range            0
hp_range            0
capture_rate       70
flee_rate          70
male_perc         159
female_perc       159
resistance          8
weakness            8
wild_avail          0
egg_avail           0
raid_avail          0
research_avail      0
shiny               0
shadow              0
pkedex_desc         0
poss_attacks        0
dtype: int64

## Dataframe Slicing

In [9]:
# dataframe slicing
# 1 sütun seçirik
df['pokemon_name']

0       Bulbasaur
1         Ivysaur
2        Venusaur
3      Charmander
4      Charmeleon
          ...
765     Runerigus
766       Falinks
767        Zacian
768     Zamazenta
769        Zarude
Name: pokemon_name, Length: 770, dtype: object

In [10]:
df.loc[:,'pokemon_name']

0       Bulbasaur
1         Ivysaur
2        Venusaur
3      Charmander
4      Charmeleon
          ...
765     Runerigus
766       Falinks
767        Zacian
768     Zamazenta
769        Zarude
Name: pokemon_name, Length: 770, dtype: object

In [11]:
# bir neçə sütun seçirik
df[['pokemon_name','category']]

    pokemon_name   category
0      Bulbasaur       Seed
1        Ivysaur       Seed
2       Venusaur       Seed
3     Charmander     Lizard
4     Charmeleon      Flame
..           ...        ...
765    Runerigus     Grudge
766      Falinks  Formation
767       Zacian    Warrior
768    Zamazenta    Warrior
769       Zarude      Rogue

[770 rows x 2 columns]

In [12]:
cols2 = ['pokemon_name','category']
df[cols2]

    pokemon_name   category
0      Bulbasaur       Seed
1        Ivysaur       Seed
2       Venusaur       Seed
3     Charmander     Lizard
4     Charmeleon      Flame
..           ...        ...
765    Runerigus     Grudge
766      Falinks  Formation
767       Zacian    Warrior
768    Zamazenta    Warrior
769       Zarude      Rogue

[770 rows x 2 columns]

In [13]:
df.loc[:, cols2]

    pokemon_name   category
0      Bulbasaur       Seed
1        Ivysaur       Seed
2       Venusaur       Seed
3     Charmander     Lizard
4     Charmeleon      Flame
..           ...        ...
765    Runerigus     Grudge
766      Falinks  Formation
767       Zacian    Warrior
768    Zamazenta    Warrior
769       Zarude      Rogue

[770 rows x 2 columns]

In [14]:
# bir sətir seçirik
df.iloc[10]

number                                                           11
pokemon_name                                                Metapod
pic_url           https://static.wikia.nocookie.net/pokemongo/im...
main_type                                                       Bug
secondary_type                                                  NaN
region                                                        Kanto
category                                                     Cocoon
height                                                        0.7 m
weight                                                       9.9 kg
pokemon_family                                      Caterpie family
attack                                                           45
defense                                                          80
stamina                                                         137
cp_range                                                     10-450
hp_range                                                     12-120
capture_rate                                                    25%
flee_rate                                                        9%
male_perc                                                       50%
female_perc                                                     50%
resistance               {'62.5%': ['Fighting', 'Grass', 'Ground']}
weakness                       {'160%': ['Fire', 'Flying', 'Rock']}
wild_avail                                                     Yes
egg_avail                                                        No
raid_avail                               Formerly  (1st tier level)
research_avail                                            Formerly
shiny                                                           Yes
shadow                                                           No
pkedex_desc       The shell covering this Pokémon's body is as h...
poss_attacks                     ['Bug Bite', 'Tackle', 'Struggle']
Name: 10, dtype: object

In [15]:
# bir neçə sətir seçirik
df.iloc[:10]

,number,pokemon_name,pic_url,main_type,secondary_type,region,category,height,weight,pokemon_family,...,resistance,weakness,wild_avail,egg_avail,raid_avail,research_avail,shiny,shadow,pkedex_desc,poss_attacks
0,1,Bulbasaur,https://static.wikia.nocookie.net/pokemongo/im...,Grass,Poison,Kanto,Seed,0.7 m,6.9 kg,Bulbasaur family,...,"{'62.5%': ['Electric', 'Fairy', 'Fighting', 'W...","{'160%': ['Fire', 'Flying', 'Ice', 'Psychic']}",Yes,No,Formerly (1st tier level),Yes,Yes,Yes,Bulbasaur can be seen napping in bright sunlig...,"['Tackle', 'Vine Whip', 'Power Whip', 'Seed Bo..."
1,2,Ivysaur,https://static.wikia.nocookie.net/pokemongo/im...,Grass,Poison,Kanto,Seed,1 m,13 kg,Bulbasaur family,...,"{'62.5%': ['Electric', 'Fairy', 'Fighting', 'W...","{'160%': ['Fire', 'Flying', 'Ice', 'Psychic']}",Yes,No,Formerly (1st tier level),No,Yes,Yes,There is a bud on this Pokémon's back. To supp...,"['Razor Leaf', 'Vine Whip', 'Power Whip', 'Slu..."
2,3,Venusaur,https://static.wikia.nocookie.net/pokemongo/im...,Grass,Poison,Kanto,Seed,2 m,100 kg,Bulbasaur family,...,"{'62.5%': ['Electric', 'Fairy', 'Fighting', 'W...","{'160%': ['Fire', 'Flying', 'Ice', 'Psychic']}",Yes,No,Formerly (3rd tier level),Formerly,Yes,Yes,Standard Pokédex description\nThere is a large...,"['Razor Leaf', 'Vine Whip', 'Petal Blizzard', ..."
3,4,Charmander,https://static.wikia.nocookie.net/pokemongo/im...,Fire,NaN,Kanto,Lizard,0.6 m,8.5 kg,Charmander family,...,"{'62.5%': ['Bug', 'Fairy', 'Fire', 'Grass', 'I...","{'160%': ['Ground', 'Rock', 'Water']}",Yes,No,Formerly (1st tier level),Yes,Yes,Yes,The flame that burns at the tip of its tail is...,"['Ember', 'Scratch', 'Flame Burst', 'Flame Cha..."
4,5,Charmeleon,https://static.wikia.nocookie.net/pokemongo/im...,Fire,NaN,Kanto,Flame,1.1 m,19 kg,Charmander family,...,"{'62.5%': ['Bug', 'Fairy', 'Fire', 'Grass', 'I...","{'160%': ['Ground', 'Rock', 'Water']}",Yes,No,Formerly (2nd tier level),Formerly,Yes,Yes,Charmeleon mercilessly destroys its foes using...,"['Ember', 'Fire Fang', 'Scratch', 'Fire Punch'..."
5,6,Charizard,https://static.wikia.nocookie.net/pokemongo/im...,Fire,Flying,Kanto,Flame,1.7 m,90.5 kg,Charmander family,...,"{'62.5%': ['Fairy', 'Fighting', 'Fire', 'Groun...","{'160%': ['Electric', 'Water'], '256%': ['Rock']}",Yes,No,Formerly (3rd tier level),No,Yes,Yes,Standard Pokédex description\nCharizard flies ...,"['Air Slash', 'Fire Spin', 'Dragon Breath', 'E..."
6,7,Squirtle,https://static.wikia.nocookie.net/pokemongo/im...,Water,NaN,Kanto,Tiny,0.5 m,9 kg,Squirtle family,...,"{'62.5%': ['Fire', 'Ice', 'Steel', 'Water']}","{'160%': ['Electric', 'Grass']}",Yes,No,Formerly (1st tier level),Yes,Yes,Yes,Squirtle's shell is not merely used for protec...,"['Bubble', 'Tackle', 'Aqua Jet', 'Aqua Tail', ..."
7,8,Wartortle,https://static.wikia.nocookie.net/pokemongo/im...,Water,NaN,Kanto,Turtle,1 m,22.5 kg,Squirtle family,...,"{'62.5%': ['Fire', 'Ice', 'Steel', 'Water']}","{'160%': ['Electric', 'Grass']}",Yes,No,Formerly (2nd tier level),No,Yes,Yes,"Its tail is large and covered with a rich, thi...","['Bite', 'Water Gun', 'Aqua Jet', 'Hydro Pump'..."
8,9,Blastoise,https://static.wikia.nocookie.net/pokemongo/im...,Water,NaN,Kanto,Shellfish,1.6 m,85.5 kg,Squirtle family,...,"{'62.5%': ['Fire', 'Ice', 'Steel', 'Water']}","{'160%': ['Electric', 'Grass']}",Yes,No,Formerly (4th tier level),Formerly,Yes,Yes,Standard Pokédex description\nBlastoise has wa...,"['Bite', 'Water Gun', 'Flash Cannon', 'Hydro P..."
9,10,Caterpie,https://static.wikia.nocookie.net/pokemongo/im...,Bug,NaN,Kanto,Worm,0.3 m,2.9 kg,Caterpie family,...,"{'62.5%': ['Fighting', 'Grass', 'Ground']}","{'160%': ['Fire', 'Flying', 'Rock']}",Yes,No,Formerly (1st tier level),Formerly,Yes,No,Caterpie has a voracious appetite. It can devo...,"['Bug Bite', 'Tackle', 'Struggle']"

In [16]:
# sətir və sütun seçirik
df.iloc[3:6,1:4]

  pokemon_name                                            pic_url main_type
3   Charmander  https://static.wikia.nocookie.net/pokemongo/im...      Fire
4   Charmeleon  https://static.wikia.nocookie.net/pokemongo/im...      Fire
5    Charizard  https://static.wikia.nocookie.net/pokemongo/im...      Fire

In [17]:
# boolean mask ilə işləyirik
# biz şərti ödəyən sətirləri seçirik (SQL-də "where" kimi)
mask = df['pokemon_name'] == 'Charizard'
df.loc[mask]

,number,pokemon_name,pic_url,main_type,secondary_type,region,category,height,weight,pokemon_family,...,resistance,weakness,wild_avail,egg_avail,raid_avail,research_avail,shiny,shadow,pkedex_desc,poss_attacks
5,6,Charizard,https://static.wikia.nocookie.net/pokemongo/im...,Fire,Flying,Kanto,Flame,1.7 m,90.5 kg,Charmander family,...,"{'62.5%': ['Fairy', 'Fighting', 'Fire', 'Groun...","{'160%': ['Electric', 'Water'], '256%': ['Rock']}",Yes,No,Formerly (3rd tier level),No,Yes,Yes,Standard Pokédex description\nCharizard flies ...,"['Air Slash', 'Fire Spin', 'Dragon Breath', 'E..."

In [18]:
df.loc[mask,cols2]

  pokemon_name category
5    Charizard    Flame

## Data cleaning and wrangling

In [19]:
# dataya bir də baxaq
df.head()

,number,pokemon_name,pic_url,main_type,secondary_type,region,category,height,weight,pokemon_family,...,resistance,weakness,wild_avail,egg_avail,raid_avail,research_avail,shiny,shadow,pkedex_desc,poss_attacks
0,1,Bulbasaur,https://static.wikia.nocookie.net/pokemongo/im...,Grass,Poison,Kanto,Seed,0.7 m,6.9 kg,Bulbasaur family,...,"{'62.5%': ['Electric', 'Fairy', 'Fighting', 'W...","{'160%': ['Fire', 'Flying', 'Ice', 'Psychic']}",Yes,No,Formerly (1st tier level),Yes,Yes,Yes,Bulbasaur can be seen napping in bright sunlig...,"['Tackle', 'Vine Whip', 'Power Whip', 'Seed Bo..."
1,2,Ivysaur,https://static.wikia.nocookie.net/pokemongo/im...,Grass,Poison,Kanto,Seed,1 m,13 kg,Bulbasaur family,...,"{'62.5%': ['Electric', 'Fairy', 'Fighting', 'W...","{'160%': ['Fire', 'Flying', 'Ice', 'Psychic']}",Yes,No,Formerly (1st tier level),No,Yes,Yes,There is a bud on this Pokémon's back. To supp...,"['Razor Leaf', 'Vine Whip', 'Power Whip', 'Slu..."
2,3,Venusaur,https://static.wikia.nocookie.net/pokemongo/im...,Grass,Poison,Kanto,Seed,2 m,100 kg,Bulbasaur family,...,"{'62.5%': ['Electric', 'Fairy', 'Fighting', 'W...","{'160%': ['Fire', 'Flying', 'Ice', 'Psychic']}",Yes,No,Formerly (3rd tier level),Formerly,Yes,Yes,Standard Pokédex description\nThere is a large...,"['Razor Leaf', 'Vine Whip', 'Petal Blizzard', ..."
3,4,Charmander,https://static.wikia.nocookie.net/pokemongo/im...,Fire,NaN,Kanto,Lizard,0.6 m,8.5 kg,Charmander family,...,"{'62.5%': ['Bug', 'Fairy', 'Fire', 'Grass', 'I...","{'160%': ['Ground', 'Rock', 'Water']}",Yes,No,Formerly (1st tier level),Yes,Yes,Yes,The flame that burns at the tip of its tail is...,"['Ember', 'Scratch', 'Flame Burst', 'Flame Cha..."
4,5,Charmeleon,https://static.wikia.nocookie.net/pokemongo/im...,Fire,NaN,Kanto,Flame,1.1 m,19 kg,Charmander family,...,"{'62.5%': ['Bug', 'Fairy', 'Fire', 'Grass', 'I...","{'160%': ['Ground', 'Rock', 'Water']}",Yes,No,Formerly (2nd tier level),Formerly,Yes,Yes,Charmeleon mercilessly destroys its foes using...,"['Ember', 'Fire Fang', 'Scratch', 'Fire Punch'..."

Gördüyünüz kimi, bzi sütunlar əslində ədədi bir məlumat saxlayır, lakin dataframe-də hansısa səbəbdən object kimi təsvir olunur. Bu sütunları biz float ya int şəklinə gətirməyə çalışacayıq.

In [20]:
# string -> float
# weight sütunu pokemonların çəkisini göstərir. lakin kg sözünə görə string olaraq göstərilir.
kg = '6.9 kg'
type(kg)

str

In [21]:
# string-i list-ə parçalayırıq
kg.split()

['6.9', 'kg']

In [22]:
# əmələ gəlmiş listin 1-ci elementini seçirik
kg.split()[0]

'6.9'

In [23]:
# və float-a çeviririk
float(kg.split()[0])

6.9

In [24]:
# bütün sütuna tətbiq edirik 
df['weight'].apply(lambda x: float(x.split()[0]))

0        6.9
1       13.0
2      100.0
3        8.5
4       19.0
       ...
765     66.6
766     62.0
767    110.0
768    210.0
769     70.0
Name: weight, Length: 770, dtype: float64

lambda funksiyası haqqında əlavə məlumat
https://www.w3schools.com/python/python_lambda.asp

In [25]:
# weight və height
df['weight'] = df['weight'].apply(lambda x: float(x.split()[0]))
df['height'] = df['height'].apply(lambda x: float(x.split()[0]))

Datada "cp_range" adlı bir sütun var. İnterval verilibsə, böyük ehtimalla bu ən kiçik və ən böyük qiymətlər intervalıdır. Biz bu sütunu 2 sütuna bölməliyik: min_cp və max_cp

In [26]:
df['cp_range']

0      12-1,115
1      19-1,699
2      33-2,720
3        10-980
4      19-1,653
         ...
765    27-2,273
766    28-2,357
767    47-3,829
768    47-3,829
769    47-3,833
Name: cp_range, Length: 770, dtype: object

In [27]:
# test üçün bir string dəyişənini təyin edirik
range_ = '12-1,115'

In [28]:
# vergülü silirik
range_.replace(',','')

'12-1115'

In [29]:
# "-" işarəsinə görə stringi parçalayırıq
range_.replace(',','').split('-')

['12', '1115']

In [30]:
# minimum seçmək üçün 1-ci elementi seçib, float tipinə çeviririk
float(range_.replace(',','').split('-')[0])

12.0

In [31]:
# maksimum seçmək üçün 2-ci elementi seçib, float tipinə çeviririk
float(range_.replace(',','').split('-')[1])

1115.0

In [32]:
# bütün range-ləri min max sütunlarına bölürük
df['cp_min'] = df['cp_range'].apply(lambda x:  x.replace(',','').split('-')[0]).astype(float)
df['cp_max'] = df['cp_range'].apply(lambda x:  x.replace(',','').split('-')[1]).astype(float)
df['hp_min'] = df['hp_range'].apply(lambda x:  x.replace(',','').split('-')[0]).astype(float)
df['hp_max'] = df['hp_range'].apply(lambda x:  x.replace(',','').split('-')[1]).astype(float)

In [33]:
df.head()

,number,pokemon_name,pic_url,main_type,secondary_type,region,category,height,weight,pokemon_family,...,raid_avail,research_avail,shiny,shadow,pkedex_desc,poss_attacks,cp_min,cp_max,hp_min,hp_max
0,1,Bulbasaur,https://static.wikia.nocookie.net/pokemongo/im...,Grass,Poison,Kanto,Seed,0.7,6.9,Bulbasaur family,...,Formerly (1st tier level),Yes,Yes,Yes,Bulbasaur can be seen napping in bright sunlig...,"['Tackle', 'Vine Whip', 'Power Whip', 'Seed Bo...",12.0,1115.0,12.0,113.0
1,2,Ivysaur,https://static.wikia.nocookie.net/pokemongo/im...,Grass,Poison,Kanto,Seed,1.0,13.0,Bulbasaur family,...,Formerly (1st tier level),No,Yes,Yes,There is a bud on this Pokémon's back. To supp...,"['Razor Leaf', 'Vine Whip', 'Power Whip', 'Slu...",19.0,1699.0,14.0,134.0
2,3,Venusaur,https://static.wikia.nocookie.net/pokemongo/im...,Grass,Poison,Kanto,Seed,2.0,100.0,Bulbasaur family,...,Formerly (3rd tier level),Formerly,Yes,Yes,Standard Pokédex description\nThere is a large...,"['Razor Leaf', 'Vine Whip', 'Petal Blizzard', ...",33.0,2720.0,17.0,162.0
3,4,Charmander,https://static.wikia.nocookie.net/pokemongo/im...,Fire,NaN,Kanto,Lizard,0.6,8.5,Charmander family,...,Formerly (1st tier level),Yes,Yes,Yes,The flame that burns at the tip of its tail is...,"['Ember', 'Scratch', 'Flame Burst', 'Flame Cha...",10.0,980.0,11.0,105.0
4,5,Charmeleon,https://static.wikia.nocookie.net/pokemongo/im...,Fire,NaN,Kanto,Flame,1.1,19.0,Charmander family,...,Formerly (2nd tier level),Formerly,Yes,Yes,Charmeleon mercilessly destroys its foes using...,"['Ember', 'Fire Fang', 'Scratch', 'Fire Punch'...",19.0,1653.0,14.0,131.0

Zəhmət olmasa "resistance" sütununa diqqət yetirək. Biz görürük ki, məlumatlar qarışıq vəziyyətdə qeydə alınıb. Gəlin təmizlik işlərimizi başlayaq :)

In [34]:
# Sütun dictionarilərdən ibarətdir
df['resistance']

0      {'62.5%': ['Electric', 'Fairy', 'Fighting', 'W...
1      {'62.5%': ['Electric', 'Fairy', 'Fighting', 'W...
2      {'62.5%': ['Electric', 'Fairy', 'Fighting', 'W...
3      {'62.5%': ['Bug', 'Fairy', 'Fire', 'Grass', 'I...
4      {'62.5%': ['Bug', 'Fairy', 'Fire', 'Grass', 'I...
                             ...
765    {'62.5%': ['Bug', 'Rock'], '39%': ['Electric',...
766                   {'62.5%': ['Bug', 'Dark', 'Rock']}
767    {'62.5%': ['Bug', 'Dark', 'Fighting'], '39%': ...
768                   {'62.5%': ['Bug', 'Dark', 'Rock']}
769    {'62.5%': ['Dark', 'Electric', 'Ghost', 'Grass...
Name: resistance, Length: 770, dtype: object

In [35]:
# test üçün 1 dənə observation götürürük
test_1 = df['resistance'][0]

In [36]:
test_1

"{'62.5%': ['Electric', 'Fairy', 'Fighting', 'Water'], '39%': ['Grass']}"

In [37]:
type(test_1)

str

In [ ]:
# sütunda saxlanılan data string tipindədi

In [38]:
# eval stringlərlə işləyir
# stringdə nə tipli data əks olunubsa həmən tipə çevirir
type(eval(test_1))

dict

In [39]:
# biz eval funksiyanı tətbiq edərək, stringdən dictionary almış oluruq
test_1 = eval(test_1)

In [40]:
test_1

{'62.5%': ['Electric', 'Fairy', 'Fighting', 'Water'], '39%': ['Grass']}

In [41]:
# dict_keys-dən elementləri götürə bilmirik
test_1.keys()[0]

TypeError: 'dict_keys' object is not subscriptable

In [42]:
# buna görə listə çeviririk
list(test_1.keys())

['62.5%', '39%']

In [43]:
for x in list(test_1.keys()):
    print('original: ',x, type(x))
    x = x.replace('%','')
    print('without %: ', x, type(x))
    x = float(x)
    print('convert to float: ', x, type(x))
    print('\n')

original:  62.5% <class 'str'>
without %:  62.5 <class 'str'>
convert to float:  62.5 <class 'float'>


original:  39% <class 'str'>
without %:  39 <class 'str'>
convert to float:  39.0 <class 'float'>

In [44]:
for key, value in test_1.items():
    print(f'key: {key} | value: {value}')
    
    for cat in value:
        print(cat, float(key.replace('%','')))
    print('\n')

key: 62.5% | value: ['Electric', 'Fairy', 'Fighting', 'Water']
Electric 62.5
Fairy 62.5
Fighting 62.5
Water 62.5


key: 39% | value: ['Grass']
Grass 39.0

In [45]:
# gəlin bu əməliyyatları bütün sütuna tətbiq edək
# map funskiyasından istifadə edərək, stringi dictionary-ə çeviririk
df.loc['resistance'] = df.loc['resistance'].map(eval)

KeyError: 'resistance'

In [46]:
# lakin nəyəsə görə bizdə xəta çıxır

In [47]:
# bizi marağlandıran sütunda 8 NAN qiyməti var.
df['resistance'].isna().sum()

8

In [48]:
# biz boolean mask istifadə edərək, NAN olmayan qiymətlərinə eval funksiyasını tətbiq edirik.
non_na_mask = ~df['resistance'].isna()
df.loc[non_na_mask,'resistance'] = df.loc[non_na_mask,'resistance'].map(eval)

In [50]:
# sütunu təmizləmək üçün funskiya yazırıq
def clean_column(row, colname):
    
    val_dict = dict()
    for key, value in row.items():
        for cat in value:
            val_dict[f'{cat} {colname}'] = float(key.replace('%',''))
    return val_dict

In [51]:
# təmiz data
df.loc[non_na_mask,'resistance'].apply(clean_column, colname='resistance')

0      {'Electric resistance': 62.5, 'Fairy resistanc...
1      {'Electric resistance': 62.5, 'Fairy resistanc...
2      {'Electric resistance': 62.5, 'Fairy resistanc...
3      {'Bug resistance': 62.5, 'Fairy resistance': 6...
4      {'Bug resistance': 62.5, 'Fairy resistance': 6...
                             ...
765    {'Bug resistance': 62.5, 'Rock resistance': 62...
766    {'Bug resistance': 62.5, 'Dark resistance': 62...
767    {'Bug resistance': 62.5, 'Dark resistance': 62...
768    {'Bug resistance': 62.5, 'Dark resistance': 62...
769    {'Dark resistance': 62.5, 'Electric resistance...
Name: resistance, Length: 762, dtype: object

In [52]:
# dataframe şəklində təmiz data
df.loc[non_na_mask,'resistance'].apply(clean_column, colname='resistance').apply(pd.Series)

,Electric resistance,Fairy resistance,Fighting resistance,Water resistance,Grass resistance,Bug resistance,Fire resistance,Ice resistance,Steel resistance,Ground resistance,Poison resistance,Ghost resistance,Flying resistance,Rock resistance,Dark resistance,Dragon resistance,Psychic resistance,Normal resistance
0,62.5,62.5,62.5,62.5,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,62.5,62.5,62.5,62.5,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,62.5,62.5,62.5,62.5,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,62.5,NaN,NaN,62.5,62.5,62.5,62.5,62.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,62.5,NaN,NaN,62.5,62.5,62.5,62.5,62.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
765,39.0,NaN,39.0,NaN,NaN,62.5,NaN,NaN,NaN,NaN,39.0,NaN,NaN,62.5,NaN,NaN,NaN,39.0
766,NaN,NaN,NaN,NaN,NaN,62.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.5,62.5,NaN,NaN,NaN
767,NaN,NaN,62.5,NaN,NaN,62.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.5,39.0,NaN,NaN
768,NaN,NaN,NaN,NaN,NaN,62.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.5,62.5,NaN,NaN,NaN
769,62.5,NaN,NaN,62.5,62.5,NaN,NaN,NaN,NaN,62.5,NaN,62.5,NaN,NaN,62.5,NaN,39.0,NaN

In [53]:
# biz təzə datanı bir dataframe-də saxlayırıq.
new_df = df.loc[~df['resistance'].isna(),'resistance'].apply(clean_column, colname='resistance').apply(pd.Series)

In [54]:
# və əsas datamızla JOIN edirik.
df = pd.merge(df, new_df, left_index=True, right_index=True)

In [55]:
# weakness sütunu üçün
df.loc[~df['weakness'].isna(),'weakness'] = df.loc[~df['weakness'].isna(),'weakness'].map(eval)
new_df2 = df.loc[~df['weakness'].isna(),'weakness'].apply(clean_column, colname='weakness').apply(pd.Series)
df = pd.merge(df, new_df2, left_index=True, right_index=True)

In [56]:
# concat (union)
t1 = df.iloc[:3]
t1

,number,pokemon_name,pic_url,main_type,secondary_type,region,category,height,weight,pokemon_family,...,Electric weakness,Grass weakness,Fighting weakness,Poison weakness,Steel weakness,Bug weakness,Fairy weakness,Dark weakness,Ghost weakness,Dragon weakness
0,1,Bulbasaur,https://static.wikia.nocookie.net/pokemongo/im...,Grass,Poison,Kanto,Seed,0.7,6.9,Bulbasaur family,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Ivysaur,https://static.wikia.nocookie.net/pokemongo/im...,Grass,Poison,Kanto,Seed,1.0,13.0,Bulbasaur family,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Venusaur,https://static.wikia.nocookie.net/pokemongo/im...,Grass,Poison,Kanto,Seed,2.0,100.0,Bulbasaur family,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
t2 = df.iloc[2:6]
t2

,number,pokemon_name,pic_url,main_type,secondary_type,region,category,height,weight,pokemon_family,...,Electric weakness,Grass weakness,Fighting weakness,Poison weakness,Steel weakness,Bug weakness,Fairy weakness,Dark weakness,Ghost weakness,Dragon weakness
2,3,Venusaur,https://static.wikia.nocookie.net/pokemongo/im...,Grass,Poison,Kanto,Seed,2.0,100.0,Bulbasaur family,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Charmander,https://static.wikia.nocookie.net/pokemongo/im...,Fire,NaN,Kanto,Lizard,0.6,8.5,Charmander family,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Charmeleon,https://static.wikia.nocookie.net/pokemongo/im...,Fire,NaN,Kanto,Flame,1.1,19.0,Charmander family,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,Charizard,https://static.wikia.nocookie.net/pokemongo/im...,Fire,Flying,Kanto,Flame,1.7,90.5,Charmander family,...,160.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
pd.concat([t1, t2])

,number,pokemon_name,pic_url,main_type,secondary_type,region,category,height,weight,pokemon_family,...,Electric weakness,Grass weakness,Fighting weakness,Poison weakness,Steel weakness,Bug weakness,Fairy weakness,Dark weakness,Ghost weakness,Dragon weakness
0,1,Bulbasaur,https://static.wikia.nocookie.net/pokemongo/im...,Grass,Poison,Kanto,Seed,0.7,6.9,Bulbasaur family,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Ivysaur,https://static.wikia.nocookie.net/pokemongo/im...,Grass,Poison,Kanto,Seed,1.0,13.0,Bulbasaur family,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Venusaur,https://static.wikia.nocookie.net/pokemongo/im...,Grass,Poison,Kanto,Seed,2.0,100.0,Bulbasaur family,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Venusaur,https://static.wikia.nocookie.net/pokemongo/im...,Grass,Poison,Kanto,Seed,2.0,100.0,Bulbasaur family,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Charmander,https://static.wikia.nocookie.net/pokemongo/im...,Fire,NaN,Kanto,Lizard,0.6,8.5,Charmander family,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Charmeleon,https://static.wikia.nocookie.net/pokemongo/im...,Fire,NaN,Kanto,Flame,1.1,19.0,Charmander family,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,Charizard,https://static.wikia.nocookie.net/pokemongo/im...,Fire,Flying,Kanto,Flame,1.7,90.5,Charmander family,...,160.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
# Venusaur 2 dəfə düşüb datamıza. Dublikatları silmək üçün .drop_duplicates() istifadə edirik.
pd.concat([t1, t2], ignore_index=True).drop_duplicates()

TypeError: unhashable type: 'dict'

In [ ]:
# amma hansısa sütuna görə bizdə xəta çıxır. xatırlayırısınızsa, resistance və weakness sütunlarını 
# biz eval edərək, dictionary-lərə çevirmişik və onların əsasında yeni sütunlar yaratmışdıq
# və biz resistance və weakness sütunlarını asanlıqla silə bilərik

In [60]:
# drop
t1.drop(['resistance','weakness'],axis=1, inplace=True)
t2.drop(['resistance','weakness'],axis=1, inplace=True)

C:\Users\abdul.quliyev\AppData\Local\Temp\ipykernel_29604\2803486491.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t1.drop(['resistance','weakness'],axis=1, inplace=True)
C:\Users\abdul.quliyev\AppData\Local\Temp\ipykernel_29604\2803486491.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  t2.drop(['resistance','weakness'],axis=1, inplace=True)

In [63]:
pd.concat([t1, t2]).drop_duplicates()

,number,pokemon_name,pic_url,main_type,secondary_type,region,category,height,weight,pokemon_family,...,Electric weakness,Grass weakness,Fighting weakness,Poison weakness,Steel weakness,Bug weakness,Fairy weakness,Dark weakness,Ghost weakness,Dragon weakness
0,1,Bulbasaur,https://static.wikia.nocookie.net/pokemongo/im...,Grass,Poison,Kanto,Seed,0.7,6.9,Bulbasaur family,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Ivysaur,https://static.wikia.nocookie.net/pokemongo/im...,Grass,Poison,Kanto,Seed,1.0,13.0,Bulbasaur family,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Venusaur,https://static.wikia.nocookie.net/pokemongo/im...,Grass,Poison,Kanto,Seed,2.0,100.0,Bulbasaur family,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Charmander,https://static.wikia.nocookie.net/pokemongo/im...,Fire,NaN,Kanto,Lizard,0.6,8.5,Charmander family,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Charmeleon,https://static.wikia.nocookie.net/pokemongo/im...,Fire,NaN,Kanto,Flame,1.1,19.0,Charmander family,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,Charizard,https://static.wikia.nocookie.net/pokemongo/im...,Fire,Flying,Kanto,Flame,1.7,90.5,Charmander family,...,160.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Eyni qaydada %-nan olan sütunları təmizləyirik

In [64]:
df['male_perc']

0      87.5%
1      87.5%
2      87.5%
3      87.5%
4      87.5%
       ...
765      50%
766      NaN
767      NaN
768      NaN
769      NaN
Name: male_perc, Length: 762, dtype: object

In [65]:
rates = [col for col in df.columns if 'rate' in col or 'perc' in col]

In [66]:
rates

['capture_rate', 'flee_rate', 'male_perc', 'female_perc']

In [67]:
df.loc[~df[rates[0]].isna(),rates[0]].apply(lambda x: float(x.replace('%','')))

0      20.0
1      10.0
2       5.0
3      20.0
4      10.0
       ...
764    30.0
765    10.0
766    20.0
767     2.0
768     2.0
Name: capture_rate, Length: 700, dtype: float64

In [68]:
for rate in rates:
    df.loc[~df[rate].isna() ,rate] = df.loc[~df[rate].isna(),rate].apply(lambda x: x.replace('%','')).astype(float)

In [69]:
# burada biz sütunun data tipini floata dəyişməliyik.

In [70]:
for rate in rates:
    df[rate] = df[rate].astype(float)

## FILL NA and Grouping

In [71]:
# NaN qiymətləri əvəzləmək istəyirik
df.columns

Index(['number', 'pokemon_name', 'pic_url', 'main_type', 'secondary_type',
       'region', 'category', 'height', 'weight', 'pokemon_family', 'attack',
       'defense', 'stamina', 'cp_range', 'hp_range', 'capture_rate',
       'flee_rate', 'male_perc', 'female_perc', 'resistance', 'weakness',
       'wild_avail', 'egg_avail', 'raid_avail', 'research_avail', 'shiny',
       'shadow', 'pkedex_desc', 'poss_attacks', 'cp_min', 'cp_max', 'hp_min',
       'hp_max', 'Electric resistance', 'Fairy resistance',
       'Fighting resistance', 'Water resistance', 'Grass resistance',
       'Bug resistance', 'Fire resistance', 'Ice resistance',
       'Steel resistance', 'Ground resistance', 'Poison resistance',
       'Ghost resistance', 'Flying resistance', 'Rock resistance',
       'Dark resistance', 'Dragon resistance', 'Psychic resistance',
       'Normal resistance', 'Fire weakness', 'Flying weakness', 'Ice weakness',
       'Psychic weakness', 'Ground weakness', 'Rock weakness',
       'Water weakness', 'Electric weakness', 'Grass weakness',
       'Fighting weakness', 'Poison weakness', 'Steel weakness',
       'Bug weakness', 'Fairy weakness', 'Dark weakness', 'Ghost weakness',
       'Dragon weakness'],
      dtype='object')

In [72]:
# drop columns we do not need
df.drop(['number','pic_url', 'resistance','weakness','wild_avail',
         'egg_avail','raid_avail','research_avail', 'shiny','shadow','pkedex_desc'],axis=1, inplace=True)

In [73]:
df.describe().columns

Index(['height', 'weight', 'attack', 'defense', 'stamina', 'capture_rate',
       'flee_rate', 'male_perc', 'female_perc', 'cp_min', 'cp_max', 'hp_min',
       'hp_max', 'Electric resistance', 'Fairy resistance',
       'Fighting resistance', 'Water resistance', 'Grass resistance',
       'Bug resistance', 'Fire resistance', 'Ice resistance',
       'Steel resistance', 'Ground resistance', 'Poison resistance',
       'Ghost resistance', 'Flying resistance', 'Rock resistance',
       'Dark resistance', 'Dragon resistance', 'Psychic resistance',
       'Normal resistance', 'Fire weakness', 'Flying weakness', 'Ice weakness',
       'Psychic weakness', 'Ground weakness', 'Rock weakness',
       'Water weakness', 'Electric weakness', 'Grass weakness',
       'Fighting weakness', 'Poison weakness', 'Steel weakness',
       'Bug weakness', 'Fairy weakness', 'Dark weakness', 'Ghost weakness',
       'Dragon weakness'],
      dtype='object')

In [74]:
cols3 = df.describe().columns

In [81]:
cols3 = cols3.insert(0,'main_type')

In [82]:
df[cols3]

,main_type,height,weight,attack,defense,stamina,capture_rate,flee_rate,male_perc,female_perc,...,Electric weakness,Grass weakness,Fighting weakness,Poison weakness,Steel weakness,Bug weakness,Fairy weakness,Dark weakness,Ghost weakness,Dragon weakness
0,Grass,0.7,6.9,118,111,128,20.0,10.0,87.5,12.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Grass,1.0,13.0,151,143,155,10.0,7.0,87.5,12.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Grass,2.0,100.0,198,189,190,5.0,5.0,87.5,12.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Fire,0.6,8.5,116,93,118,20.0,10.0,87.5,12.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Fire,1.1,19.0,158,126,151,10.0,7.0,87.5,12.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
765,Ground,1.6,66.6,163,237,151,10.0,7.0,50.0,50.0,...,NaN,160.0,NaN,NaN,NaN,NaN,NaN,160.0,160.0,NaN
766,Fighting,3.0,62.0,193,170,163,20.0,10.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,160.0,NaN,NaN,NaN
767,Fairy,2.8,110.0,254,236,192,2.0,10.0,NaN,NaN,...,NaN,NaN,NaN,160.0,160.0,NaN,NaN,NaN,NaN,NaN
768,Fighting,2.9,210.0,254,236,192,2.0,10.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,160.0,NaN,NaN,NaN
769,Dark,1.8,70.0,242,215,233,NaN,NaN,NaN,NaN,...,NaN,NaN,160.0,160.0,NaN,256.0,160.0,NaN,NaN,NaN

In [83]:
# biz nan qiymətləri müvafiq MAİN_TYPE-ın mean qiymətlərilə əvəzləyək. Bunun üçün bizə group by
# lazım olacaq

In [84]:
# Group by müxtəlif yollarla yazıla bilər

In [85]:
# method 1
df.groupby('pokemon_family').max()[['height','weight','attack','defense']]

C:\Users\abdul.quliyev\AppData\Local\Temp\ipykernel_29604\1802313242.py:2: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  df.groupby('pokemon_family').max()[['height','weight','attack','defense']]

                   height  weight  attack  defense
pokemon_family
Abra family           1.5    56.5     271      167
Absol family          1.2    47.0     246      120
Aerodactyl family     1.8    59.0     221      159
Aipom family          1.2    20.3     205      143
Alomomola family      1.2    31.6     138      131
...                   ...     ...     ...      ...
Zekrom family         2.9   345.0     275      211
Zigzagoon family      1.6    46.0     180      194
Zorua family          1.6    81.1     250      127
Zubat family          1.8    75.0     194      178
Zygarde family        4.5   610.0     203      232

[389 rows x 4 columns]

In [86]:
# method 2
df.groupby('pokemon_family').agg({"height":['mean','max','min'],
                                  "weight":[np.mean,np.max,np.min],
                                 "attack":[np.mean,'max','min']})

                     height                 weight                    attack  \
                       mean  max   min        mean   amax   amin        mean
pokemon_family
Abra family        1.233333  1.5  0.90   41.333333   56.5   19.5  232.666667
Absol family       1.200000  1.2  1.20   47.000000   47.0   47.0  246.000000
Aerodactyl family  1.800000  1.8  1.80   59.000000   59.0   59.0  221.000000
Aipom family       0.995000  1.2  0.79   15.900000   20.3   11.5  170.500000
Alomomola family   1.200000  1.2  1.20   31.600000   31.6   31.6  138.000000
...                     ...  ...   ...         ...    ...    ...         ...
Zekrom family      2.900000  2.9  2.90  345.000000  345.0  345.0  275.000000
Zigzagoon family   0.833333  1.6  0.40   32.000000   46.0   17.5  126.666667
Zorua family       1.150000  1.6  0.70   46.800000   81.1   12.5  201.500000
Zubat family       1.400000  1.8  0.80   45.833333   75.0    7.5  146.000000
Zygarde family     4.500000  4.5  4.50  610.000000  610.0  610.0  203.000000


                   max  min
pokemon_family
Abra family        271  195
Absol family       246  246
Aerodactyl family  221  221
Aipom family       205  136
Alomomola family   138  138
...                ...  ...
Zekrom family      275  275
Zigzagoon family   180   58
Zorua family       250  153
Zubat family       194   83
Zygarde family     203  203

[389 rows x 9 columns]

In [87]:
# method 3
df.groupby(['main_type','secondary_type']).agg({'height':['max','min','mean']})\
.sort_values(by=('height','max'))

                         height
                            max   min      mean
main_type secondary_type
Electric  Ghost            0.30  0.30  0.300000
Psychic   Fire             0.40  0.40  0.400000
          Ghost            0.50  0.50  0.500000
Poison    Water            0.50  0.50  0.500000
Bug       Ground           0.51  0.51  0.510000
...                         ...   ...       ...
Dark      Flying           5.80  0.50  1.782000
Water     Flying           6.50  0.50  1.887143
Dragon    Flying           7.01  1.10  2.952500
Rock      Ground           8.80  0.40  2.233333
Steel     Ground           9.20  9.20  9.200000

[128 rows x 3 columns]

In [91]:
# pivot tables
# burada biz iki categorical dəyişənlərə görə group by etmiş oluruq
pd.pivot_table(df,values='height',columns='main_type',index='secondary_type',\
               aggfunc=['max','min','mean'])

                 max                                                          \
main_type        Bug  Dark Dragon Electric Fairy Fighting  Fire Flying Ghost
secondary_type
Bug              NaN   NaN    NaN      NaN   NaN      NaN   NaN    NaN   NaN
Dark             NaN   NaN    NaN      NaN   NaN      2.1   NaN    NaN   1.0
Dragon           NaN  1.80    NaN      NaN   NaN      NaN   NaN    1.5   4.5
Electric        0.80   NaN   2.90      NaN   NaN      NaN   NaN    NaN   NaN
Fairy            NaN   NaN    NaN      1.8   NaN      NaN   NaN    NaN   NaN
Fighting        1.50  1.10    NaN      NaN   NaN      NaN  1.91    NaN   NaN
Fire            1.60  1.40   3.20      NaN   NaN      NaN   NaN    NaN   1.0
Flying          1.90  5.80   7.01      1.6   1.5      0.8  3.81    NaN   1.2
Ghost           0.79  0.51    NaN      0.3   NaN      NaN   NaN    NaN   NaN
Grass           1.20  1.80    NaN      NaN   NaN      NaN   NaN    NaN   1.5
Ground          0.51   NaN   4.50      NaN   NaN      NaN  1.91    NaN   NaN
Ice              NaN  1.10   3.00      NaN   NaN      NaN   NaN    NaN   NaN
Normal           NaN  1.60    NaN      1.0   NaN      NaN  1.50    NaN   NaN
Poison          2.50   NaN    NaN      NaN   NaN      NaN   NaN    NaN   1.6
Psychic          NaN  1.50   2.01      NaN   NaN      1.3  1.50    NaN   NaN
Rock            1.40   NaN    NaN      NaN   NaN      NaN  0.79    NaN   NaN
Steel           2.01  1.60    NaN      1.2   NaN      1.2  1.70    NaN   NaN
Water           0.51   NaN    NaN      NaN   NaN      NaN  1.70    NaN   NaN

                      ...      mean                                          \
main_type      Grass  ...     Ghost     Grass    Ground       Ice    Normal
secondary_type        ...
Bug              NaN  ...       NaN       NaN       NaN       NaN       NaN
Dark            1.30  ...  1.000000  1.196667  1.066667       NaN       NaN
Dragon           NaN  ...  4.500000       NaN  1.550000       NaN       NaN
Electric         NaN  ...       NaN       NaN  0.700000       NaN       NaN
Fairy           1.90  ...       NaN  0.966667       NaN       NaN  0.500000
Fighting        2.00  ...       NaN  1.596667       NaN       NaN  1.300000
Fire             NaN  ...  0.633333       NaN       NaN       NaN       NaN
Flying          2.01  ...  0.800000  0.803333  1.530000  1.295000  0.812692
Ghost            NaN  ...       NaN       NaN  1.800000  1.300000       NaN
Grass            NaN  ...  0.800000       NaN       NaN       NaN  1.250000
Ground          2.20  ...       NaN  2.200000       NaN  1.333333  1.000000
Ice             2.20  ...       NaN  1.600000       NaN       NaN       NaN
Normal           NaN  ...       NaN       NaN       NaN       NaN       NaN
Poison          2.00  ...  1.466667  0.842857       NaN       NaN       NaN
Psychic         2.00  ...       NaN  1.200000  1.005000  1.103333  1.200000
Rock             NaN  ...       NaN       NaN  1.766667       NaN       NaN
Steel           1.00  ...       NaN  0.800000  0.700000       NaN       NaN
Water            NaN  ...       NaN       NaN       NaN  1.093333  1.000000


main_type      Poison   Psychic      Rock     Steel     Water
secondary_type
Bug              0.80       NaN  1.105000       NaN       NaN
Dark             0.90       NaN  2.010000       NaN  1.295000
Dragon           1.80       NaN  1.650000  5.400000  3.000000
Electric          NaN       NaN       NaN       NaN  0.850000
Fairy             NaN  0.983333  0.500000  0.405000  1.075000
Fighting         1.00  1.600000  1.900000  2.100000  1.350000
Fire              NaN  0.400000       NaN       NaN       NaN
Flying           1.40  1.601667  1.233333  1.700000  1.887143
Ghost             NaN  0.500000       NaN  1.100000  1.700000
Grass             NaN  0.610000  1.245000       NaN  1.066667
Ground           1.35       NaN  2.233333  9.200000  0.946667
Ice               NaN       NaN  2.000000       NaN  1.900000
Normal            NaN       NaN       NaN       NaN       NaN
Poison            NaN       NaN       NaN       NaN  1.003333
Psychic           NaN       NaN  1.090000  0.916667  1.475000
Rock              NaN       NaN       NaN  1.136667  0.875000
Steel             NaN       NaN  1.066667       NaN  1.700000
Water            0.50       NaN  0.833333       NaN       NaN

[18 rows x 54 columns]

In [92]:
# NAN qiymətlər olan sütunları seçirik
na_df = df.T[df.isna().sum() > 0].T

In [93]:
na_df

,secondary_type,capture_rate,flee_rate,male_perc,female_perc,Electric resistance,Fairy resistance,Fighting resistance,Water resistance,Grass resistance,...,Electric weakness,Grass weakness,Fighting weakness,Poison weakness,Steel weakness,Bug weakness,Fairy weakness,Dark weakness,Ghost weakness,Dragon weakness
0,Poison,20.0,10.0,87.5,12.5,62.5,62.5,62.5,62.5,39.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Poison,10.0,7.0,87.5,12.5,62.5,62.5,62.5,62.5,39.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Poison,5.0,5.0,87.5,12.5,62.5,62.5,62.5,62.5,39.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,20.0,10.0,87.5,12.5,NaN,62.5,NaN,NaN,62.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,10.0,7.0,87.5,12.5,NaN,62.5,NaN,NaN,62.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
765,Ghost,10.0,7.0,50.0,50.0,39.0,NaN,39.0,NaN,NaN,...,NaN,160.0,NaN,NaN,NaN,NaN,NaN,160.0,160.0,NaN
766,NaN,20.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,160.0,NaN,NaN,NaN
767,NaN,2.0,10.0,NaN,NaN,NaN,NaN,62.5,NaN,NaN,...,NaN,NaN,NaN,160.0,160.0,NaN,NaN,NaN,NaN,NaN
768,NaN,2.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,160.0,NaN,NaN,NaN
769,Grass,NaN,NaN,NaN,NaN,62.5,NaN,NaN,62.5,62.5,...,NaN,NaN,160.0,160.0,NaN,256.0,160.0,NaN,NaN,NaN

In [94]:
# secondary type bizə maraqlı deyil, biz onu drop edə bilərik

In [95]:
na_df.drop('secondary_type',axis=1, inplace=True)

In [97]:
# MEAN qiymətini fərqli yollarla tapa bilərik. NAN qiymətlər nəzərə alınmır

In [98]:
df['capture_rate'].mean()

24.2

In [99]:
np.mean(df['capture_rate'])

24.2

In [100]:
df[~df['capture_rate'].isna()]['capture_rate'].mean()

24.2

In [101]:
# Meanlərdən ibarət cədvəl
means = df.groupby('main_type').mean()

In [102]:
means

,height,weight,attack,defense,stamina,capture_rate,flee_rate,male_perc,female_perc,cp_min,...,Electric weakness,Grass weakness,Fighting weakness,Poison weakness,Steel weakness,Bug weakness,Fairy weakness,Dark weakness,Ghost weakness,Dragon weakness
main_type,,,,,,,,,,,,,,,,,,,,,
Bug,0.863651,29.361905,137.714286,131.412698,146.730159,26.103175,9.666667,50.669643,49.330357,18.936508,...,160.000000,NaN,NaN,160.000000,160.000000,160.000000,160.000000,160.000000,160.0,NaN
Dark,1.183667,41.060000,179.066667,142.100000,170.066667,21.910714,8.285714,54.500000,45.500000,24.966667,...,160.000000,NaN,181.818182,160.000000,160.000000,176.000000,178.461538,NaN,NaN,160.0
Dragon,1.960800,123.704000,202.000000,163.960000,180.560000,14.217391,5.260870,50.000000,50.000000,31.760000,...,NaN,NaN,160.000000,NaN,160.000000,160.000000,160.000000,160.000000,160.0,160.0
Electric,0.920270,36.989189,175.297297,134.108108,154.270270,22.852941,7.970588,54.166667,45.833333,23.297297,...,NaN,NaN,160.000000,160.000000,NaN,NaN,NaN,160.000000,160.0,NaN
Fairy,0.901053,28.105263,159.368421,156.842105,176.578947,17.812500,8.000000,51.923077,48.076923,24.631579,...,160.000000,NaN,NaN,160.000000,160.000000,NaN,NaN,NaN,NaN,NaN
Fighting,1.282857,62.932143,180.928571,135.321429,172.392857,23.826923,7.961538,63.750000,36.250000,25.071429,...,160.000000,NaN,160.000000,NaN,NaN,NaN,163.555556,NaN,160.0,NaN
Fire,1.127400,60.792000,179.460000,135.500000,168.480000,17.200000,7.933333,68.313953,31.686047,24.560000,...,160.000000,NaN,160.000000,NaN,NaN,NaN,NaN,160.000000,160.0,NaN
Flying,1.166667,52.000000,184.666667,137.333333,168.666667,19.000000,5.000000,50.000000,50.000000,28.000000,...,160.000000,NaN,NaN,NaN,NaN,NaN,160.000000,NaN,NaN,160.0
Ghost,1.160870,57.008696,167.782609,151.173913,156.173913,21.391304,7.521739,50.000000,50.000000,22.391304,...,160.000000,NaN,NaN,NaN,NaN,NaN,160.000000,160.000000,160.0,160.0
Grass,0.971972,36.594366,153.478873,138.295775,165.408451,23.390625,8.359375,62.701613,37.298387,21.253521,...,NaN,NaN,160.000000,165.333333,160.000000,171.162791,160.000000,160.000000,160.0,NaN
Ground,1.220000,103.496774,168.548387,148.903226,174.903226,24.725806,8.096774,50.000000,50.000000,24.645161,...,NaN,171.520000,160.000000,NaN,160.000000,160.000000,160.000000,160.000000,160.0,160.0
Ice,1.220417,101.383333,168.166667,152.125000,176.375000,21.250000,8.333333,52.083333,47.916667,25.041667,...,160.000000,160.000000,160.000000,NaN,160.000000,160.000000,NaN,160.000000,160.0,NaN
Normal,0.962762,41.445714,145.447619,121.380952,182.457143,29.342391,9.717391,48.323171,51.676829,20.485714,...,160.000000,160.000000,160.000000,160.000000,160.000000,160.000000,160.000000,160.000000,NaN,NaN
Poison,1.214286,36.621429,144.500000,133.500000,167.321429,29.464286,9.071429,50.000000,50.000000,19.642857,...,160.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,160.0
Psychic,0.952917,29.377083,177.687500,153.083333,173.208333,24.851351,10.729730,51.102941,48.897059,25.791667,...,160.000000,NaN,NaN,160.000000,160.000000,162.909091,160.000000,162.341463,162.0,NaN
Rock,1.292326,96.867442,170.906977,168.930233,163.837209,24.269231,7.871795,70.357143,29.642857,24.627907,...,160.000000,197.161290,176.941176,NaN,171.294118,160.000000,160.000000,160.000000,160.0,160.0
Steel,1.533200,171.512000,160.360000,193.920000,165.440000,20.159091,7.681818,50.000000,50.000000,25.880000,...,160.000000,NaN,182.153846,NaN,NaN,NaN,NaN,160.000000,160.0,NaN
Water,1.310917,52.437615,154.614679,141.522936,172.954128,26.892157,8.480392,58.762887,41.237113,22.000000,...,167.225806,173.419355,160.000000,160.000000,NaN,160.000000,160.000000,160.000000,160.0,160.0

In [103]:
# gəlin NA olan sütunlara bir də nəzər yetirək

In [104]:
na_df

,capture_rate,flee_rate,male_perc,female_perc,Electric resistance,Fairy resistance,Fighting resistance,Water resistance,Grass resistance,Bug resistance,...,Electric weakness,Grass weakness,Fighting weakness,Poison weakness,Steel weakness,Bug weakness,Fairy weakness,Dark weakness,Ghost weakness,Dragon weakness
0,20.0,10.0,87.5,12.5,62.5,62.5,62.5,62.5,39.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10.0,7.0,87.5,12.5,62.5,62.5,62.5,62.5,39.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5.0,5.0,87.5,12.5,62.5,62.5,62.5,62.5,39.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20.0,10.0,87.5,12.5,NaN,62.5,NaN,NaN,62.5,62.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10.0,7.0,87.5,12.5,NaN,62.5,NaN,NaN,62.5,62.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
765,10.0,7.0,50.0,50.0,39.0,NaN,39.0,NaN,NaN,62.5,...,NaN,160.0,NaN,NaN,NaN,NaN,NaN,160.0,160.0,NaN
766,20.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.5,...,NaN,NaN,NaN,NaN,NaN,NaN,160.0,NaN,NaN,NaN
767,2.0,10.0,NaN,NaN,NaN,NaN,62.5,NaN,NaN,62.5,...,NaN,NaN,NaN,160.0,160.0,NaN,NaN,NaN,NaN,NaN
768,2.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62.5,...,NaN,NaN,NaN,NaN,NaN,NaN,160.0,NaN,NaN,NaN
769,NaN,NaN,NaN,NaN,62.5,NaN,NaN,62.5,62.5,NaN,...,NaN,NaN,160.0,160.0,NaN,256.0,160.0,NaN,NaN,NaN

In [ ]:
# cədvəlimi 2 hissədən ibarətdir. 1) ratelər 2) resistance və weakness
# rateləri mean qiymətnən əvəzləyəyəcik.

In [105]:
mean_cols = na_df.columns[:4]

In [106]:
mean_cols

Index(['capture_rate', 'flee_rate', 'male_perc', 'female_perc'], dtype='object')

In [110]:
# biz main_type-a görə map edirik və müvafiq mean qiymətini NAN əvəzinə yazırıq
nan_mask = df['capture_rate'].isna()
df.loc[nan_mask,'capture_rate']

150   NaN
171   NaN
172   NaN
173   NaN
174   NaN
       ..
753   NaN
754   NaN
755   NaN
756   NaN
769   NaN
Name: capture_rate, Length: 62, dtype: float64

In [111]:
df.loc[nan_mask, 'main_type']

150     Psychic
171    Electric
172       Fairy
173      Normal
174       Fairy
         ...
753       Grass
754       Water
755       Steel
756       Steel
769        Dark
Name: main_type, Length: 62, dtype: object

In [112]:
df.loc[nan_mask,'main_type'].map(means['capture_rate'])

150    24.851351
171    22.852941
172    17.812500
173    29.342391
174    17.812500
         ...
753    23.390625
754    26.892157
755    20.159091
756    20.159091
769    21.910714
Name: main_type, Length: 62, dtype: float64

In [118]:
# koda fikir verməsəniz olar. bizim məqsədimiz capture_rate NAN qiymətlərini müvafiq ədədlərlə əvəzləməkdir
pd.merge(df.loc[nan_mask,'capture_rate'],\
         (pd.merge(df.loc[nan_mask, 'main_type'], df.loc[nan_mask,'main_type'].map(means['capture_rate']),\
         left_index=True, right_index=True, suffixes=['','_mean'])),left_index=True,right_index=True)

     capture_rate main_type  main_type_mean
150           NaN   Psychic       24.851351
171           NaN  Electric       22.852941
172           NaN     Fairy       17.812500
173           NaN    Normal       29.342391
174           NaN     Fairy       17.812500
..            ...       ...             ...
753           NaN     Grass       23.390625
754           NaN     Water       26.892157
755           NaN     Steel       20.159091
756           NaN     Steel       20.159091
769           NaN      Dark       21.910714

[62 rows x 3 columns]

In [119]:
# biz main_type-a görə map edirik və müvafiq mean qiymətini NAN əvəzinə yazırıq
for col in mean_cols:
    print(col)
    nan_mask = df[col].isna()
    df.loc[nan_mask,col] = df.loc[nan_mask, 'main_type'].map(means[col])

capture_rate
flee_rate
male_perc
female_perc

In [120]:
# NaN qiymətlər olan sütunlar (secondary nəzərə almırıq)
df.T[df.isna().sum() > 0].T.columns

Index(['secondary_type', 'Electric resistance', 'Fairy resistance',
       'Fighting resistance', 'Water resistance', 'Grass resistance',
       'Bug resistance', 'Fire resistance', 'Ice resistance',
       'Steel resistance', 'Ground resistance', 'Poison resistance',
       'Ghost resistance', 'Flying resistance', 'Rock resistance',
       'Dark resistance', 'Dragon resistance', 'Psychic resistance',
       'Normal resistance', 'Fire weakness', 'Flying weakness', 'Ice weakness',
       'Psychic weakness', 'Ground weakness', 'Rock weakness',
       'Water weakness', 'Electric weakness', 'Grass weakness',
       'Fighting weakness', 'Poison weakness', 'Steel weakness',
       'Bug weakness', 'Fairy weakness', 'Dark weakness', 'Ghost weakness',
       'Dragon weakness'],
      dtype='object')

In [121]:
res_weak_cols = df.T[df.isna().sum() > 0].T.columns[1:]

In [122]:
res_weak_cols

Index(['Electric resistance', 'Fairy resistance', 'Fighting resistance',
       'Water resistance', 'Grass resistance', 'Bug resistance',
       'Fire resistance', 'Ice resistance', 'Steel resistance',
       'Ground resistance', 'Poison resistance', 'Ghost resistance',
       'Flying resistance', 'Rock resistance', 'Dark resistance',
       'Dragon resistance', 'Psychic resistance', 'Normal resistance',
       'Fire weakness', 'Flying weakness', 'Ice weakness', 'Psychic weakness',
       'Ground weakness', 'Rock weakness', 'Water weakness',
       'Electric weakness', 'Grass weakness', 'Fighting weakness',
       'Poison weakness', 'Steel weakness', 'Bug weakness', 'Fairy weakness',
       'Dark weakness', 'Ghost weakness', 'Dragon weakness'],
      dtype='object')

In [123]:
# məntiqə əsasən, resistance NAN qeyd olunubsa, o zaman Resistance yoxdur.
# Bu məntiqlə, biz NAN qiymətlərini 0-la əvəz edə bilərik (0 resistance = no resistance)

In [124]:
df[res_weak_cols]

,Electric resistance,Fairy resistance,Fighting resistance,Water resistance,Grass resistance,Bug resistance,Fire resistance,Ice resistance,Steel resistance,Ground resistance,...,Electric weakness,Grass weakness,Fighting weakness,Poison weakness,Steel weakness,Bug weakness,Fairy weakness,Dark weakness,Ghost weakness,Dragon weakness
0,62.5,62.5,62.5,62.5,39.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,62.5,62.5,62.5,62.5,39.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,62.5,62.5,62.5,62.5,39.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,62.5,NaN,NaN,62.5,62.5,62.5,62.5,62.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,62.5,NaN,NaN,62.5,62.5,62.5,62.5,62.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
765,39.0,NaN,39.0,NaN,NaN,62.5,NaN,NaN,NaN,NaN,...,NaN,160.0,NaN,NaN,NaN,NaN,NaN,160.0,160.0,NaN
766,NaN,NaN,NaN,NaN,NaN,62.5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,160.0,NaN,NaN,NaN
767,NaN,NaN,62.5,NaN,NaN,62.5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,160.0,160.0,NaN,NaN,NaN,NaN,NaN
768,NaN,NaN,NaN,NaN,NaN,62.5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,160.0,NaN,NaN,NaN
769,62.5,NaN,NaN,62.5,62.5,NaN,NaN,NaN,NaN,62.5,...,NaN,NaN,160.0,160.0,NaN,256.0,160.0,NaN,NaN,NaN

In [132]:
df[res_weak_cols] = df[res_weak_cols].fillna(0)

In [133]:
df[res_weak_cols]

,Electric resistance,Fairy resistance,Fighting resistance,Water resistance,Grass resistance,Bug resistance,Fire resistance,Ice resistance,Steel resistance,Ground resistance,...,Electric weakness,Grass weakness,Fighting weakness,Poison weakness,Steel weakness,Bug weakness,Fairy weakness,Dark weakness,Ghost weakness,Dragon weakness
0,62.5,62.5,62.5,62.5,39.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,62.5,62.5,62.5,62.5,39.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,62.5,62.5,62.5,62.5,39.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,62.5,0.0,0.0,62.5,62.5,62.5,62.5,62.5,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,62.5,0.0,0.0,62.5,62.5,62.5,62.5,62.5,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
765,39.0,0.0,39.0,0.0,0.0,62.5,0.0,0.0,0.0,0.0,...,0.0,160.0,0.0,0.0,0.0,0.0,0.0,160.0,160.0,0.0
766,0.0,0.0,0.0,0.0,0.0,62.5,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,160.0,0.0,0.0,0.0
767,0.0,0.0,62.5,0.0,0.0,62.5,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,160.0,160.0,0.0,0.0,0.0,0.0,0.0
768,0.0,0.0,0.0,0.0,0.0,62.5,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,160.0,0.0,0.0,0.0
769,62.5,0.0,0.0,62.5,62.5,0.0,0.0,0.0,0.0,62.5,...,0.0,0.0,160.0,160.0,0.0,256.0,160.0,0.0,0.0,0.0

In [134]:
# Secondary Type olmadığı halda biz None-la əvəzləyirik

In [135]:
df['secondary_type'].fillna('None', inplace=True)

In [136]:
df

,pokemon_name,main_type,secondary_type,region,category,height,weight,pokemon_family,attack,defense,...,Electric weakness,Grass weakness,Fighting weakness,Poison weakness,Steel weakness,Bug weakness,Fairy weakness,Dark weakness,Ghost weakness,Dragon weakness
0,Bulbasaur,Grass,Poison,Kanto,Seed,0.7,6.9,Bulbasaur family,118,111,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Ivysaur,Grass,Poison,Kanto,Seed,1.0,13.0,Bulbasaur family,151,143,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Venusaur,Grass,Poison,Kanto,Seed,2.0,100.0,Bulbasaur family,198,189,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Charmander,Fire,None,Kanto,Lizard,0.6,8.5,Charmander family,116,93,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Charmeleon,Fire,None,Kanto,Flame,1.1,19.0,Charmander family,158,126,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
765,Runerigus,Ground,Ghost,Galar,Grudge,1.6,66.6,Yamask family,163,237,...,0.0,160.0,0.0,0.0,0.0,0.0,0.0,160.0,160.0,0.0
766,Falinks,Fighting,None,Galar,Formation,3.0,62.0,Falinks family,193,170,...,0.0,0.0,0.0,0.0,0.0,0.0,160.0,0.0,0.0,0.0
767,Zacian,Fairy,None,Galar,Warrior,2.8,110.0,Zacian family,254,236,...,0.0,0.0,0.0,160.0,160.0,0.0,0.0,0.0,0.0,0.0
768,Zamazenta,Fighting,None,Galar,Warrior,2.9,210.0,Zamazenta family,254,236,...,0.0,0.0,0.0,0.0,0.0,0.0,160.0,0.0,0.0,0.0
769,Zarude,Dark,Grass,Galar,Rogue,1.8,70.0,Zarude family,242,215,...,0.0,0.0,160.0,160.0,0.0,256.0,160.0,0.0,0.0,0.0

In [137]:
df.isna().sum()

pokemon_name           0
main_type              0
secondary_type         0
region                 0
category               0
height                 0
weight                 0
pokemon_family         0
attack                 0
defense                0
stamina                0
cp_range               0
hp_range               0
capture_rate           0
flee_rate              0
male_perc              0
female_perc            0
poss_attacks           0
cp_min                 0
cp_max                 0
hp_min                 0
hp_max                 0
Electric resistance    0
Fairy resistance       0
Fighting resistance    0
Water resistance       0
Grass resistance       0
Bug resistance         0
Fire resistance        0
Ice resistance         0
Steel resistance       0
Ground resistance      0
Poison resistance      0
Ghost resistance       0
Flying resistance      0
Rock resistance        0
Dark resistance        0
Dragon resistance      0
Psychic resistance     0
Normal resistance      0
Fire weakness          0
Flying weakness        0
Ice weakness           0
Psychic weakness       0
Ground weakness        0
Rock weakness          0
Water weakness         0
Electric weakness      0
Grass weakness         0
Fighting weakness      0
Poison weakness        0
Steel weakness         0
Bug weakness           0
Fairy weakness         0
Dark weakness          0
Ghost weakness         0
Dragon weakness        0
dtype: int64

In [138]:
# Gördüyünüz kimi, NaN qiymətləri biz təmizlədik və işimizin növbəti mərhələsinə keçə bilərik.